### ISSUE TITLE
opposite problem - ExplorerBrowser does not get dark

### ISSUE THREAD

**Issue by AdmiralSnyder** [dbrookes96/ExplorerBrowserTest#1]
hi, i kinda have the opposite problem:
i have a c# winforms usercontrol with the ExplorerBrowser com object attached to it, and i want it to match a given color theme - the only thing that successfully happens is that the toolbars are colored appropriately. i'm trying everything (using SetWindowTheme, for example) to get it to become dark... yet, no success. here's a screenshot:
![image](https://user-images.githubusercontent.com/16213022/152988703-ceab2509-50e4-45da-a22e-2d8b13c6a4cd.png)

except yesterday, for a brief period, the item background was black. but i don't know how that happened, since it was in the VS instance i had the project in, not in the debuggee. . . (sadly, i didn't take a screenshot)
i suppose it must have something to do with the system waking up from sleep or hibernation... trying to repro it...

i'll see if i can get similar behaviour when creating a dialog. gotta find how you did that :-P

**Comment by AdmiralSnyder** [comment]
![image](https://user-images.githubusercontent.com/16213022/152990075-a059ddab-9d97-47f8-b1aa-071f11a4460e.png)
this is the OpenFileDialog that's opened... - no change in style within the listview.
![image](https://user-images.githubusercontent.com/16213022/152990156-94e08bb2-9ea5-4599-9737-714fc81a8f8d.png)
this is how my explorer windows look, usually.
![image](https://user-images.githubusercontent.com/16213022/152990194-66e5362c-16d0-4914-9112-aea7e8e48103.png)

**Comment by AdmiralSnyder** [comment]
this on the other hand is the openfiledialog when `this` is being vien as owner...
![image](https://user-images.githubusercontent.com/16213022/152990625-6efd16ec-af56-4686-a8cb-3d1c99b16984.png)
--> expected darkmode.

**Comment by AdmiralSnyder** [comment]
and now, after exiting the dialog, i get the color change in font color:
![image](https://user-images.githubusercontent.com/16213022/152990817-f4d36fae-09ea-4448-9c65-46bb3b7c1e74.png)

**Comment by AdmiralSnyder** [comment]
... and after navigating, the background is dark, too:
![image](https://user-images.githubusercontent.com/16213022/152991108-5ce84693-37cc-47f6-81e6-f9528da90deb.png)

**Comment by dbrookes96** [comment]
Hi, thanks for reaching out!

I'm glad to know I'm not the only one having problems with this control 🙂

I think what your seeing is a similar to problem as what I described in the README. I have also tried hacking around with `SetWindowTheme` with `DarkMode_Explorer` to try force this into dark mode with no success. Being able to support that in our applications would be a bonus. But really I would just like it not to glitch out.

At this point I've just been thinking about maybe no longer using this control in favour of a custom shell list view control. There are some UI toolkits out there that provide them. That lacks some of the features that the proper explorer browser provides though so its not a _good_ solution.

I had an issue open on the developer community linking to this github, but it was closed due to "not enough information provided". I'm not really hopeful this will ever get fixed. I guess if more people are having the problem its possible it might get looked at.

**Comment by AdmiralSnyder** [comment]
hi, i got mine to reliably go to darkmode by calling the

**Comment by dbrookes96** [comment]
Wow okay that's great. I'll need to give that a go myself and I'll update this repository if so. I was aware of some of those undocumented APIs but I haven't actually tried them out.

Thanks for the tip!

**Comment by dbrookes96** [comment]
Looks like setting the preferred app mode did the trick!

I've updated the repository with that and have included some of those utilities in <code>ThemeManager.cpp</code>.

Thanks for your help 🙂

**Comment by dbrookes96** [comment]
One more thing I forgot to mention. It does look like it still messes up with <code>PreferredAppMode::ForceDark</code> and <code>PreferredAppMode::ForceLight</code>. I found its best to just use <code>PreferredAppMode::AllowDark</code> and just obey whatever the users colour preference was.

**Comment by AdmiralSnyder** [comment]
hey, do you still get a white background while loading the window?

**Comment by dbrookes96** [comment]
No I don't believe so, but its possible its loading quick enough for me not to see it.

Does that happen when the Explorer Browser is created for the first time, or every time you change folders?

**Comment by AdmiralSnyder** [comment]
only at first time creation - though it's in a VS instance that is debugged, so not the fastest thing in the world.

**Comment by dbrookes96** [comment]
Yes I think I am actually seeing that same behaviour. It was harder to notice since the explorer browser isn't initially visible in the actual application I've been working on. We similarly put it in a docking pane kind of thing. The explorer browser has a white-ish background after calling initialize, but before we actually navigate it somewhere. 

I had a bit of a mess around with it but couldn't find anything obvious. I guess the explorer browser just creates its internal view on demand. 

I suppose a workaround would be to only initialize the explorer browser COM object only when your going to navigate it for the first time. That way the dark theme background of the pane, or whatever is your parent window, should be able to be visible.

By the way while I was playing with this I noticed the <code>EBO_NOBORDER</code> flag. Looks a bit nicer when this is inside a pane since you don't get a double border 🙂
